config/routes.rb
Ticketee::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :projects do
        resources :tickets
      end
    end
  end

  namespace :api do
    namespace :v2 do
      resources :projects do
        resources :tickets
      end
    end
  end
  get "users/index"

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => 'users/omniauth_callbacks' }
  get '/awaiting_confirmation', :to => 'users#confirmation', :as => 'confirm_user'

  root :to => "projects#index"
  resources :projects do
    resources :tickets do
      collection do
        get :search
      end
      member do
        post :watch
      end
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end

  resources :files

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end

  put '/admin/users/:user_id/permissions', :to => 'admin/permissions#update', :as => :update_user_permissions

  mount Forem::Engine, :at => "/forem"

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name

  has_many :tickets, :dependent => :delete_all
  has_many :permissions, :as => :thing

  validates :name, :presence => true, :uniqueness => true

  scope :readable_by, lambda { |user| joins(:permissions).where(:permissions => { :action => "view", :user_id => user.id }) }

  def self.for(user)
    user.admin? ? Project : Project.readable_by(user)
  end

  def last_ticket
    tickets.last
  end

  def title
    name
  end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::V1::BaseController
  before_filter :authorize_admin!, :except => [:index, :show]
  before_filter :find_project, :only => [:show, :update, :destroy]
  def index
    respond_with(Project.for(current_user))
  end

  def create
    project = Project.create(params[:project])
    if project.valid?
      respond_with(project, :location => api_v1_project_path(project))
    else
      respond_with(project)
    end
  end

  def show
    respond_with(@project, :methods => "last_ticket")
  end

  def update
    @project.update_attributes(params[:project])
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private

  def find_project
    @project = Project.for(current_user).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      error = { :error => "The project you were looking for could not be found." }
      respond_with(error, :status => 404)
  end
end

app/controllers/api/v2/projects_controller.rb
class Api::V2::ProjectsController < Api::V2::BaseController
  before_filter :authorize_admin!, :except => [:index, :show]
  before_filter :find_project, :only => [:show, :update, :destroy]
  def index
    respond_with(Project.readable_by(current_user), :except => :name, :methods => :title)
  end

  def create
    project = Project.create(params[:project])
    if project.valid?
      respond_with(project, :location => api_v2_project_path(project))
    else
      respond_with(project)
    end
  end

  def show
    respond_with(@project, :methods => "last_ticket")
  end

  def update
    @project.update_attributes(params[:project])
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private

  def find_project
    @project = Project.for(current_user).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      error = { :error => "The project you were looking for could not be found." }
      respond_with(error, :status => 404)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authorize_admin!, :except => [:index, :show]    
  before_filter :authenticate_user!, :only => [:index, :show]    
  before_filter :find_project, :only => [:show, :edit, :update, :destroy]

  #caches_action :show, :cache_path => (proc do
  #  project_path(params[:id]) + "/#{current_user.id}/#{params[:page] || 1}"
  #end)

  def index
    @projects = Project.for(current_user).all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to @project, :notice => "Project has been created."
    else
      flash[:alert] = "Project has not been created."
      render 'new'
    end
  end

  def show
    @tickets = @project.tickets.page(params[:page])
  end

  def edit
  end

  def update
    if @project.update_attributes(params[:project])
      redirect_to @project, :notice => "Project has been updated."
    else
      flash[:alert] = "Project has not been updated."
      render "edit"
    end
  end

  def destroy
    if @project.destroy
      redirect_to projects_path, :notice => "Project has been deleted."
    else
      flash[:alert] = "Project has not been deleted."
      render "index"
    end
  end

  private
    def find_project
      @project = Project.for(current_user).find(params[:id])
      rescue ActiveRecord::RecordNotFound

      flash[:alert] = "The project you were looking for could not be found."
      redirect_to projects_path
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% @project.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
  <p>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </p>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>
<%= render "form" %>

app/views/projects/index.html.erb
<h2>Projects</h2>
<ul id='projects'>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>
<%= admins_only do %>
  <%= link_to "New Project", new_project_path %>
<% end %>

app/views/projects/new.html.erb
<h2>New Project</h2>
<%= render "form" %>

app/views/projects/show.html.erb
<% title(@project.name,"Projects") %>
<h2><%= @project.name %></h2>
<%= admins_only do %>
  <%= link_to "Edit Project", edit_project_path(@project) %>
  <%= link_to "Delete Project", @project, :method => :delete, :confirm => "Are you sure you want to delete this project?" %>
<% end %>

<%= authorized?("create tickets".to_sym, @project) do %>
  <%= link_to "New Ticket", new_project_ticket_path(@project) %>
<% end %>
<%= form_tag search_project_tickets_path(@project), :method => :get do %>
  <%= label_tag 'search' %>
  <%= text_field_tag "search", params[:search] %>
  <%= submit_tag "Search" %>
<% end %>
<% cache "projects/#{@project.id}/#{params[:page] || 1}" do %>  
  <%= paginate @tickets %>
  <ul id="tickets">
    <% @tickets.each do |ticket| %>
      <li>
      <%= render ticket.state if ticket.state %>
      #<%= ticket.id %> - <%= link_to ticket.title, [@project, ticket] %>
      </li>
    <% end %>
  </ul>
<% end %>