config/routes.rb
Ticketee::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :projects do
        resources :tickets
      end
    end
  end

  namespace :api do
    namespace :v2 do
      resources :projects do
        resources :tickets
      end
    end
  end
  get "users/index"

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => 'users/omniauth_callbacks' }
  get '/awaiting_confirmation', :to => 'users#confirmation', :as => 'confirm_user'

  root :to => "projects#index"
  resources :projects do
    resources :tickets do
      collection do
        get :search
      end
      member do
        post :watch
      end
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end

  resources :files

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end

  put '/admin/users/:user_id/permissions', :to => 'admin/permissions#update', :as => :update_user_permissions

  mount Forem::Engine, :at => "/forem"

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def remove
    @ticket = Ticket.find(params[:ticket_id])
    if can?(:tag, @ticket.project) || current_user.admin?
      @tag = Tag.find(params[:id])
      @ticket.tags -= [@tag]

      @ticket.save
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<p>
  <%= label_tag :tags %>
  <%= text_field_tag :tags, params[:tags] %>
</p>

app/views/tags/_tag.html.erb
<span class='tag' id='tag-<%= tag.name.parameterize %>'>
  <% if can?(:tag, @ticket.project) || current_user.admin? %>
    <%= link_to "x", remove_ticket_tag_path(@ticket, tag),:remote => true, :method => :delete, :id => "delete-#{tag.name.parameterize}" %>
  <% end %>
  <%= link_to tag.name, search_project_tickets_path(@ticket.project, :search => "tag:#{tag.name}") %>
</span>

app/views/tags/remove.js.erb
$('#tag-<%= @tag.name.parameterize %>').remove();