config/routes.rb
Ticketee::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :projects do
        resources :tickets
      end
    end
  end

  namespace :api do
    namespace :v2 do
      resources :projects do
        resources :tickets
      end
    end
  end
  get "users/index"

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => 'users/omniauth_callbacks' }
  get '/awaiting_confirmation', :to => 'users#confirmation', :as => 'confirm_user'

  root :to => "projects#index"
  resources :projects do
    resources :tickets do
      collection do
        get :search
      end
      member do
        post :watch
      end
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end

  resources :files

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end

  put '/admin/users/:user_id/permissions', :to => 'admin/permissions#update', :as => :update_user_permissions

  mount Forem::Engine, :at => "/forem"

end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :background, :color, :name

  def default!
    current_default_state = State.find_by_default(true)
    self.default = true
    self.save!

    if current_default_state
      current_default_state.default = false
      current_default_state.save!
    end
  end

  def to_s
    name
  end
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < Admin::BaseController
  before_filter :find_state, :except => [:new, :create, :index]
  def new
    @state = State.new
  end

  def create
    @state = State.new(params[:state])

    if @state.save
      flash[:notice] = 'State has been created.'
      redirect_to admin_states_path
    else
      flash[:error] = "State has not been created."
      render :action => "new"
    end
  end

  def update
    if @state.update_attributes(params[:state])
      flash[:notice] = 'State has been updated.'
      redirect_to admin_states_path
    else
      flash[:error] = 'State has not been updated.'
      render :action => "edit"
    end
  end

  def destroy
    @state.destroy
    flash[:notice] = "State has been deleted."
    redirect_to admin_states_path
  end

  def make_default
    @state.default!
    flash[:notice] = "#{@state.name} is now the default state."
    redirect_to admin_states_path
  end

  private
  def find_state
    @state = State.find(params[:id])
  end
end

app/views/admin/states/_form.html.erb
<%= form_for [:admin, @state] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <%= f.submit %>
<% end %>

app/views/admin/states/edit.html.erb
<h4>Edit State</h4>
<%= render 'form' %>

app/views/admin/states/index.html.erb
<ul id='states'>
  <% for state in @states %>
    <li id = 'state_<%= state.id %>'>
      <%= link_to state.name, admin_state_path(state) %>
      <% if state.default? %>
        (Default)
      <% else %>
        <%= link_to "Make default", make_default_admin_state_path(state) %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "New State", new_admin_state_path %>

app/views/admin/states/new.html.erb
<h2>New State</h2>
<%= render 'form' %>

app/views/admin/states/show.html.erb
<h4><%= @state.name %></h4>
<%= link_to "Edit State", edit_admin_state_path(@state) %>
<%= link_to "Delete State", admin_state_path(@state), :confirm => "Are you sure you want to delete this state?", :method => :delete %>